### ISSUE TITLE
Kandidáti bez životopisu

### ISSUE THREAD

**Issue by AloisSeckar** [svobodni/ballot_box#22]
Vyřešit, aby se kandidátům, kteří nedodali svůj životopis v PDF, buďto nezobrazoval odkaz "CV", nebo aby vedl na vysvětlující stránku místo generické chybové "No site"

**Comment by dqd** [comment]
Pokud ten odkaz chceme zrušit, bude potřeba rozšířit registr, aby posílal informaci o životopisu.

**Comment by me2d09** [comment]
Uzavírám, zdá se že vyřešeno v registru.
