### ISSUE TITLE
Omezení věku pro kandidáty

### ISSUE THREAD

**Issue by AloisSeckar** [svobodni/ballot_box#23]
Pro primárky do senátu a na prezidenta omezit vstupní věk kandidátů tak, aby mohli do voleb opravdu kandidovat...musí mu být 40 let (pozor - ke dni voleb)

p.s. konfrontovat s Všeobecnými pravidly pro výběr kandidátů a v případě potřeby doplnit text o toto potřebné omezení - nemá rozhodně cenu vybrat primárkami kandidáta, co nemůže následně kandidovat...

**Comment by dqd** [comment]
Podle mě je tenhle požadavek nesplnitelný, protože my v době kandidatury obvykle nevíme, kdy se volby budou konat. Tohle se musí ohlídat při schvalování kandidátek.

**Comment by me2d09** [comment]
Souhlasím s dqd, tohle se dá ohlídat ručně.
