### ISSUE TITLE
Více informací o skončených volbách

### ISSUE THREAD

**Issue by dqd** [svobodni/ballot_box#27]
Z podnětu našeho člena: „U skončených voleb by se mohla pro úplnost zobrazovat informace, zda člověk volil (a u voleb po určitém datu i informace, zda se zdržel nebo vůbec neměl hlasovací právo – to u těch dřívějších nepůjde rozlišit).“

**Comment by me2d09** [comment]
Přidána informace, jestli člověk volil nebo ne.
Nedá se zjistit, jestli člověk měl či neměl hlasovací právo. Je možné že v době volby nebyl členem a nyní je a tak by to vypadalo, že mohl volit.
