### ISSUE TITLE
Pridat hlasovani organu

### ISSUE THREAD

**Issue by cocosx** [svobodni/ballot_box#6]
Kdo muze hlasovani vyvolat?
Na jakych urovnich?
Hlasovani tajne nebo verejne?
Vysledek tajny nebo verejny?
Jen pro/proti nebo i vice moznosti?

**Comment by cocosx** [comment]
Kdo může hlasování vyvolat: Vyvolat a zadat per rollam hlasování může předseda orgánu (pro ReP, ReV předseda strany + za Macha zmocněnec (v současnosti Pořízek) na jeho pokyn),

Na jakých úrovních: Ve všech orgánech. Tedy ReP, ReV, RK, KK, VK, všechny KrPy.

Veřejné/tajné možnost zvolit. Podle stanov se normálně nehlasuje tajně, ale hlasuje se tajně, "když o to požádá kterýkoliv člen" - (orgánu) - takže možnost tajného hlasování per rollam by měla být zachována. (typicky personální otázky)

Výsledek bude přístupný jen členům orgánu a všem třem komisím. Doklady o hlasování - tedy protokol - se přikládají k zápisu. Protokol by měl obsahovat jména hlasujících a jak hlasovali vždy, když nepůjde o tajnou volbu.

Musí být možnost jak pro/proti, tak i více možností. Prostě to musí být obecné.

Prosím ostatní, aby to po mne zkontrolovali a případně se k tomu vyjádřili. Zatím bych do toho nezatahoval pobočky, ty koneckonců nemají žádnou rozhodovací pravomoc, i když v pravidlech poboček je, myslím, cosi o hlasování.

Dále panuje shoda, že VS se o tyto volby nebude nějak moc starat, že to bude automatizované.  VS neni “majitelem” těch voleb - na rozdíl od voleb KrPů, primárek atd… VS bude  jen “dozorovat” systém.

**Comment by AloisSeckar** [comment]
já si myslím, že by výsledky měly být viditelné všem členům (co je na nich tajného?)

a podle mě nemá smysl zavádět per rollam na něco jiného než pro/proti...všechny usnesení je tak třeba formulovat...

**Comment by me2d09** [comment]
Tenhle issue chce více specifikovat. Já bych to rozdělil:
- [ ]  Umožnit veřejnou volbu - každá volba pújde udělat veřejně, po skončení se pak ukáže, jak kdo hlasoval.
- [ ]  Umožnit vytvářet volby dalším lidem - tohle chce promyslet jak moc je to vhodné. Imo by to využíval stejně jen ReV - ostatní orgány jsou malé a udělají si hlasování po svém.

Výsledek všech hlasování bych nechal vždy přístupný všem členům/příznivcům. Přijde mi nesmysl to tajit.

**Comment by AloisSeckar** [comment]
Je otázka, zda je vůbec ještě akuální. Per-rollam ReVu už nyní umíme (v roce 2015 to afaik ještě nešlo). 

Pokud by mělo být per-rollam i pro RePy, komise a KrPy, tak to podle mě má smysl jen, pokud by to bylo "povinné" vždy - a ne že si někdo dál pojede po mailech. To by zřejmě vyžadovalo usnesení Sněmu, které to uvede do praxe - a změnu jednacích řádů. Skoro bych se do toho vůbec nepouštěl, leda když poptávka po takových per-rollamech v budoucnu reálně vznikne. Teď si nemyslím, že to někdo řeší. Pro <= 5členné orgány je imho i efektivnější hlasovat emailem než zadávat něco někam do systému (a pak stejně přijde email, že má člověk jít hlasovat).

Jediným potenciálním úkolem tak je viditelnost hlasování, což nyní nejde - a na to bych kdyžtak otevřel separátní issue. Viditelnost výsledků však musí být volitelná, protože ve Stanovách je právo člena požádat o tajné hlasování. Myslím si, že by i měla být nastavitelná v průběhu volby, protože si dovedu představit, že o to člen ReV požádá až po vyhlášení per-rollam (až poté, co se z notifikace dozví, že byla volba předsedou vyhlášena).

**Comment by me2d09** [comment]
Hlasovani lze udelat pro jakekoli jednotky, takze to co ted delame pro ReV jde i pro ReP ci KrP.
Pro netajne hlasovani udelam novou issue az se vratim z dovolene (utery) a tohle tedy zaviram.
