### ISSUE TITLE
Přidání odkazu na úložiště protokolů

### ISSUE THREAD

**Issue by peepo68** [svobodni/ballot_box#9]
Prosím přidat na hlavní stránku VS viditelný odkaz - tlačítko  - na protokoly na files
https://files.svobodni.cz/vk/pro-členy/

**Comment by cocosx** [comment]
Ted je to udelano tak, ze databaze protokolu je primou soucasti volebniho systemu.
Ale pridam stranku s jejich kompletnim vypisem.
